stages:
  - test_entry

test_some_name1:
  image: ros:galactic
  stage: test_entry
  script:
    - apt update && apt install tree
    - uname -a
    - echo $CI_JOB_NAME
    - ls -alF
    - tree / -L 2
    - printenv
    - tree /opt/ros/galactic -L 2
  artifacts:
    name: "$CI_JOB_NAME"
